# Generated by Django 2.2.19 on 2021-04-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='field1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
